name: Check linter

on: [pull_request]

jobs:
  npm-run-lint:
    runs-on: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: npm install and lint
        run: |
          npm install
          npm run lint
